config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :trials
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trial.rb
class Trial < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	
	before_save { self.email = email.downcase }
	
	before_save { self.phone = phone.to_i }
	
	validates :name,		 presence: true, length: { minimium: 2, maximum: 15 }
	validates :phone,		 presence: true
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, 	 presence: true, length: { maximum: 255 },
																																 uniqueness: { case_sensitive: false },
																																 format: { with: VALID_EMAIL_REGEX }
	
	validates :password, presence: true, length: { minimum: 6 }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
	  def logged_in_user
	  	unless logged_in?
	  		flash[:danger] = "Please, Log in."
	  		redirect_to login_url
	  	end
	  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Wrong email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  
  def new
    @trial = Trial.new
  end
  
  def create
    @trial = Trial.new(trial_params)
    if @trial.save
      flash[:success] = "Trial created successfully"
      redirect_to trials_path
    else
      render 'new'
    end
  end

  def show
    @trial = Trial.find(params[:id])
  end

  def index
    @trials = Trial.all
  end
  
  private
  
    def trial_params
      params.require(:trial).permit(:title, :description, :enrollment_start, :enrollment_end)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,       only:   [:show, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user,   only:   [:edit, :update, :destroy]
  before_action :admin_user,     only:   [:destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'You created a new account'
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Account updated'
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :first_name, :last_name)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id] = user.id
	end
	
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def current_user?(user)
		current_user == user
	end
	
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<ul>
  <li><%= link_to 'Home', root_url %></li>
  <% if !logged_in? %>
    <li><%= link_to 'Login', login_url %></li>
    <li><%= link_to 'Signup', signup_url %></li>
  <% else %>
    <li><%= link_to 'Profile',  current_user %></li>
    <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
  	<li><%= link_to 'Logout', 	logout_url, method: :delete %></li>
  <% end %>
</ul>

<style>
	ul li
	{
		display: inline;
		padding-right: 10px;
	}
	
	li:first-child
	{
		padding-right: 30px;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Randomized Trials</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul class="alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Welcome to Randomized Trials</h1>

<%= link_to "Propose a trial", new_trial_path, class:"btn btn-primary", role:"button" %>
<br> <br>
<%= link_to "Browse trials", trials_path, class:"btn btn-info", role:"button" %>

app/views/trials/_trial.html.erb
<p>
	<h4><%= trial.title %></h4>
	<p><%= trial.description %></p>
	<small>Enrollment start at: <%= trial.enrollment_start %></small>
	<br>
	<small>Enrollment ends at: <%= trial.enrollment_end %></small>
</p>

app/views/trials/index.html.erb
<h1>Trials:</h1>

<%= render @trials %>

app/views/trials/new.html.erb
<h1>Propose a trial:</h1>

<%= form_for(@trial) do |f| %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	
	<p>
		<%= f.label :enrollment_start %>
		<%= f.text_field :enrollment_start, class: "enrollment" %>
	</p>
	
	<p>
		<%= f.label :enrollment_end %>
		<%= f.text_field :enrollment_end, class: "enrollment" %>
	</p>
	
	<%= f.submit "Submit" %>

<% end %>

app/views/trials/show.html.erb
<h1>Trials#show</h1>
<p>Find me in app/views/trials/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	<%= render 'shared/error_messages', object: f.object %>

	<p>
		<%= f.label "Username*" %>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label "Email*" %>
		<%= f.text_field :email %>
	</p>
	
	<p>
		<%= f.label "Password*" %>
		<%= f.password_field :password %>
	</p>
	
	<p>
		<%= f.label "Password confirmation*" %>
		<%= f.password_field :password_confirmation %>
	</p>
	
	<p>
		<%= f.label "Phone*" %>
		<%= f.text_field :phone %>
	</p>
	
	<p>
		<%= f.label "Firstname" %>
		<%= f.text_field :first_name %>
	</p>
	
	<p>
		<%= f.label "Last_name" %>
		<%= f.text_field :last_name %>
	</p>
	
	<%= f.submit 'Submit' %>

<% end %>

app/views/users/edit.html.erb
<h1>Settings</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h3><%= @user.name.capitalize %></h3>